### ISSUE TITLE
Error  No such file or directory

### ISSUE THREAD

**Issue by remster85** [cls1991/ng#2]
```
remster@DESKTOP-XXX:~/ng$ python ng.py ip
192.168.1.110
XXXXXX

remster@DESKTOP-XXX:~/ng$ python ng.py wp
Traceback (most recent call last):
  File "ng.py", line 133, in <module>
    cli()
  File "/home/remster/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/remster/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/remster/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/remster/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/remster/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "ng.py", line 116, in wp
    ok, err = _detect_wifi_ssid()
  File "ng.py", line 41, in _detect_wifi_ssid
    rs = _exec(command)
  File "ng.py", line 25, in _exec
    out, err = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

or 
```

remster@DESKTOP-V1MD90G:~/ng$ python3 ng.py wp
Traceback (most recent call last):
  File "ng.py", line 133, in <module>
    cli()
  File "/home/remster/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/remster/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/remster/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/remster/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/remster/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "ng.py", line 116, in wp
    ok, err = _detect_wifi_ssid()
  File "ng.py", line 41, in _detect_wifi_ssid
    rs = _exec(command)
  File "ng.py", line 25, in _exec
    out, err = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'nm-tool'
```

**Comment by cls1991** [comment]
What’s your os?

**Comment by cls1991** [comment]
@remster85  What’ your os?

**Comment by remster85** [comment]
Ubuntu 16.04.3 LTS

**Comment by cls1991** [comment]
@remster85 It seems nm-tool is no longer available since Ubuntu 15.04, it's replaced by nmcli. 
I will fix it later.

**Comment by cls1991** [comment]
@remster85 Fixed!

**Comment by remster85** [comment]
Thanks for your reactivity! I have pulled your changed, the error has changed.

`b''b'\n(process:12778): nmcli-CRITICAL **: Error: Could not create NMClient object: Could not connect: No such file or directory.\n'`

I have edited the network manager config file as suggested [here](https://bbs.archlinux.org/viewtopic.php?id=143640) and I also have installed some kits following the following [Topic](https://askubuntu.com/questions/363945/networkmanager-broken-after-upgrade-to-kubuntu-saucy)

I am fairly new to unix.

**Comment by cls1991** [comment]
The nmcli is installed deault in Ubuntu 16.04, just type:

    $ nmcli dev wifi

I'm glad to see the outputs.

**Comment by remster85** [comment]
```
remster@DESKTOP-V1MD90G:~/ng$ nmcli dev wifi

(process:12788): nmcli-CRITICAL **: Error: Could not create NMClient object: Could not connect: No such file or directory.
```

**Comment by cls1991** [comment]
Sorry for that,  you may have a try to reinstall nmcli, good luck!

**Comment by remster85** [comment]
Isn't any compatibility issue with the latest ubuntu?

https://askubuntu.com/questions/991072/issues-with-nmcli-on-ubuntu-16-04-3-lts

**Comment by cls1991** [comment]
flyfish13@ubuntu:~$ lsb_release -a
       No LSB modules are available.
       Distributor ID:	Ubuntu
       Description:	Ubuntu 16.04.3 LTS
       Release:	16.04
       Codename:	xenial

       flyfish13@ubuntu:~$ nmcli
       Usage: nmcli [OPTIONS] OBJECT { COMMAND | help }

       OPTIONS
       -t[erse]                                   terse output
       -p[retty]                                  pretty output
       -m[ode] tabular|multiline                  output mode
       -c[olors] auto|yes|no                      whether to use colors in output
       -f[ields] <field1,field2,...>|all|common   specify fields to output
       -e[scape] yes|no                           escape columns separators in values
       -a[sk]                                     ask for missing parameters
       -s[how-secrets]                            allow displaying passwords
       -w[ait] <seconds>                          set timeout waiting for finishing operations
       -v[ersion]                                 show program version
       -h[elp]                                    print this help

       OBJECT
       g[eneral]       NetworkManager's general status and operations
       n[etworking]    overall networking control
       r[adio]         NetworkManager radio switches
       c[onnection]    NetworkManager's connections
       d[evice]        devices managed by NetworkManager
       a[gent]         NetworkManager secret agent or polkit agent
       m[onitor]       monitor NetworkManager changes
